# Generated by Django 4.1.10 on 2023-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandirModel',
            fields=[
                ('mandir_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandir_name', models.CharField(max_length=50)),
                ('mandir_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mandir_date', models.DateField()),
                ('timings', models.CharField(max_length=100)),
                ('mandir_isfor', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
